### ISSUE TITLE
Text box input too small for user to see their prompts

### ISSUE THREAD

**Issue by St80ene** [CodeLeom/resume-checker#1]
- The text box input for prompts should be changed to textare input
- User should be able to see their text clearly e.g User input on OpenAI ChaGPT for prompts.

**Comment by CodeLeom** [comment]
@St80ene kindly work on this issue

**Comment by St80ene** [comment]
Already on it. Thanks

**Comment by St80ene** [comment]
[PR](https://github.com/CodeLeom/resume-checker/pull/2) raised for this issue
